// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD709Zzxk5943dV1OHHUCIQuR0ydkUPn0k',
    appId: '1:243366168728:web:68cd0a0cd05da426ba68ed',
    messagingSenderId: '243366168728',
    projectId: 'tyamo-app391',
    authDomain: 'tyamo-app391.firebaseapp.com',
    storageBucket: 'tyamo-app391.firebasestorage.app',
    measurementId: 'G-62V1X56QR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqN8HWE0By6JpO2RpU1KXfjwJdXA_pnEM',
    appId: '1:243366168728:android:e721b77a583d0fd0ba68ed',
    messagingSenderId: '243366168728',
    projectId: 'tyamo-app391',
    storageBucket: 'tyamo-app391.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH1WaGevtMQhbgSZy8Q1AhIQts27NlIQs',
    appId: '1:243366168728:ios:3e117c4f13652df8ba68ed',
    messagingSenderId: '243366168728',
    projectId: 'tyamo-app391',
    storageBucket: 'tyamo-app391.firebasestorage.app',
    iosBundleId: 'com.example.tyamo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH1WaGevtMQhbgSZy8Q1AhIQts27NlIQs',
    appId: '1:243366168728:ios:3e117c4f13652df8ba68ed',
    messagingSenderId: '243366168728',
    projectId: 'tyamo-app391',
    storageBucket: 'tyamo-app391.firebasestorage.app',
    iosBundleId: 'com.example.tyamo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD709Zzxk5943dV1OHHUCIQuR0ydkUPn0k',
    appId: '1:243366168728:web:d7dfb3aac0b995c4ba68ed',
    messagingSenderId: '243366168728',
    projectId: 'tyamo-app391',
    authDomain: 'tyamo-app391.firebaseapp.com',
    storageBucket: 'tyamo-app391.firebasestorage.app',
    measurementId: 'G-VKSDVYJ31G',
  );
}
